// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6D0ymkxc47lxbMMLsS8kAbrAVW7wevL0',
    appId: '1:178915042787:android:cddb8e40192d617cb4acd6',
    messagingSenderId: '178915042787',
    projectId: 'tiyatro-c307e',
    databaseURL: 'https://tiyatro-c307e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tiyatro-c307e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7sS8v1gEA3mS6h5bs1l7wiiUw2mXAHKM',
    appId: '1:178915042787:ios:251c6d36b15151a3b4acd6',
    messagingSenderId: '178915042787',
    projectId: 'tiyatro-c307e',
    databaseURL: 'https://tiyatro-c307e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tiyatro-c307e.appspot.com',
    iosBundleId: 'com.example.tiyatrokulubu',
  );
}
